# Generated by Django 4.2 on 2025-02-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('card', 'Card '), ('hero_slide', 'Hero Slayt'), ('service', 'Service'), ('team_member', 'Team Member')], max_length=50),
        ),
    ]
