# Generated by Django 4.2 on 2025-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
