# Generated by Django 4.2 on 2025-02-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='extra_data',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
