# Generated by Django 4.2 on 2025-02-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_content_extra_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('portfolio', 'Portfolio Card'), ('hero_slide', 'Hero Slayt'), ('service', 'Service'), ('team_member', 'Team Member'), ('clients', 'Clients'), ('comments', 'Comments'), ('features', 'Features')], max_length=50),
        ),
    ]
