# Generated by Django 4.2 on 2025-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('portfolio', 'Portfolio Card'), ('hero_slide', 'Hero Slayt'), ('service', 'Service'), ('team_member', 'Team Member'), ('clients', 'Clients'), ('comments', 'Comments'), ('features', 'Features'), ('blog', 'Blog')], max_length=50),
        ),
    ]
